### ISSUE TITLE
Doesn't minify html-files outside of 'assets'

### ISSUE THREAD

**Issue by jepz** [tolyo/html-pages-brunch#7]
Had installed  brunch  by
`$ brunch new proj -s es6`,
 istalled your plugin 
`npm install --save-dev html-pages-brunch`
Added my HTML files outside of the folder app/assets, so they are now stored in app.

running `brunch build --production` does not add files in the folder public.

Is there any configuration I'm missing?

**Comment by tolyo** [comment]
You may be overriding `conventions.assets` setting to ignore `.html` files. Can you show your `config` please.

**Comment by jepz** [comment]
I tried to add everything that could be added just to make it work somehow.
File brunch-config.js:

```
module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'vendor.js': /^(?!app)/,
        'app.js': /^app/
      }
    },
    stylesheets: {joinTo: 'css/app.css'}
  },

  plugins: {
      babel: {presets: ['es2015']},
      htmlPages: {
            htmlMin: {
              caseSensitive: false,
              collapseBooleanAttributes: true,
              collapseInlineTagWhitespace: false,
              collapseWhitespace: true,
              conservativeCollapse: false,
              html5: true,
              includeAutoGeneratedTags: false,
              keepClosingSlash: false,
              minifyCSS: true,
              minifyJS: true,
              preserveLineBreaks: false,
              preventAttributesEscaping: false,
              processConditionalComments: true,
              removeAttributeQuotes: true,
              removeComments: true,
              removeEmptyAttributes: true,
              removeOptionalTags: true,
              removeScriptTypeAttributes: true,
              removeStyleLinkTypeAttributes: true,
              sortAttributes: true,
              sortClassName: true    
            },
            destination(path) {
              return path.replace(/^app[\/\\](.*)\.html$/, "$1.html");
            },
            disabled: false
          }

  }
};

```

**Comment by tolyo** [comment]
I see it now. Please downgrade to `2.0.6` while I fix this

**Comment by jepz** [comment]
I downgraded to `2.0.6` but html-files in "app" does not get modified and moved to "Public".

Amnythings else I can show you?

**Comment by tolyo** [comment]
I meant `2.0.5` :) I am fixing this. Hang on

**Comment by tolyo** [comment]
Published `2.2.0`. Try it.

**Comment by jepz** [comment]
Alright! it now adds files into public, but the comments aren't removed...

**Comment by jepz** [comment]
..and "collapseWhitespace" doesn't work either...

**Comment by tolyo** [comment]
Set `optimize` to `true`

**Comment by jepz** [comment]
Nice! works lovely, do i need to keep all the other options or is "optimize" enough?

**Comment by tolyo** [comment]
Well `optimize` gets turned to `true` by default for build prod. So you can safely ignore it while `watch -s`.

**Comment by tolyo** [comment]
I should document that....

**Comment by jepz** [comment]
;-) yes you should.

Thanks for the help!

**Comment by tolyo** [comment]
Np
